name: Mvel LSP

on:
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

permissions:
  contents: read

jobs:
  mvel-lsp-build:
    concurrency:
      group: mven-lsp-${{ matrix.os }}-${{ matrix.java-version }}-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        java-version: [17, 21]
        maven-version: ['3.9.12']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Java Setup
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Setup
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: ${{ matrix.maven-version }}

      - name: Checkout mvel/mvel main branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: mvel/mvel
          ref: main
          path: mvel

      - name: Build mvel/mvel main branch
        run: mvn -B clean install -DskipTests
        working-directory: ./mvel

      - name: Build with Maven
        run: mvn -B clean install

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - run: npm ci
        working-directory: ./client

      - name: Extension E2E Test for Linux
        run: xvfb-run -a npm test
        working-directory: ./client
        if: runner.os == 'Linux'

      - name: Extension E2E Test for Windows
        run: npm test
        working-directory: ./client
        if: runner.os == 'Windows'

      - name: Extension E2E Test for MacOS
        run: GHA_JAVA_HOME=$JAVA_HOME npm test
        working-directory: ./client
        if: runner.os == 'macOS'
