name: Tag Release CI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: '3.9.12'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install
      - run: mkdir staging && cp mvel3-lsp-server/target/mvel3-lsp-server-jar-with-dependencies.jar staging

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - run: npm ci
        working-directory: ./client

      - name: Extension E2E Test
        run: xvfb-run -a npm test
        working-directory: ./client

      - name: Package VS Code Extension
        working-directory: ./client
        run: |
          npm run pack:dev
          cp dist/*.vsix ../staging/

      - uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: |
            staging/*.jar
            staging/*.vsix
